// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvptilaacgqfuxvkwlvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2cHRpbGFhY2dxZnV4dmt3bHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Nzk2OTQsImV4cCI6MjA3MjM1NTY5NH0.TI7JbxRyreYLnUaDF0b2rHlmY4eTxUgMptBtfuqKy1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});